format_version: 10
pipelines:
  release_tests_1_pipeline:
    group: st_1_group
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    secure_variables:
      DATADOG_API_KEY: AES:HW23CeCfgdBIZjgqX2GcNQ==:6BWHun00t+JdzZ6/qPuNjo34ov5ch7BM5I/nqTjhgoH7WYnYc/kCmJzKE66VgrqW
      DATADOG_APP_KEY: AES:CmXeb/HLv5whaaV/vwEaag==:SUK7PIbfR4pU4ZJCzbVJSTg8hxF1AancZrjllJ+X0M6k5Ccg0yTTn/iRHmtlrtuy
    materials:
      git-1eda989:
        git: https://github.com/edx/edx-gocd-synthetic-testing.git
        type: configrepo
        shallow_clone: false
        auto_update: true
        branch: dd-tests-fresh
        destination: synthetic-testing
      tubular:
        git: https://github.com/edx/tubular
        blacklist:
          - '**/*'
        shallow_clone: true
        auto_update: true
        branch: bszabo/synthetic-testing
        destination: tubular
    stages:
    - release_tests_1_stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          run_release_tests_job1:
            timeout: 0
            elastic_profile_id: legacy-default
            tasks:
            - exec:
                arguments:
                - Hello, world, from job 1
                command: echo
                run_if: passed
          run_release_tests_job2:
            timeout: 0
            elastic_profile_id: legacy-default
            tasks:
            - exec:
                arguments:
                - -c
                - pwd
                command: /bin/bash
                run_if: passed
          run_release_tests_job3:
            timeout: 0
            elastic_profile_id: legacy-default
            tasks:
            - exec:
                arguments:
                - ./tubular/scripts/dd_synthetic_tests.py
                - '--enable-automated-rollbacks'
                command: python3
                working_directory: tubular
                run_if: passed
