format_version: 10
pipelines:
  release_tests_3:
    group: synthetic_testing_3
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    secure_variables:
      DATADOG_API_KEY: AES:HW23CeCfgdBIZjgqX2GcNQ==:6BWHun00t+JdzZ6/qPuNjo34ov5ch7BM5I/nqTjhgoH7WYnYc/kCmJzKE66VgrqW
      DATADOG_APP_KEY: AES:CmXeb/HLv5whaaV/vwEaag==:SUK7PIbfR4pU4ZJCzbVJSTg8hxF1AancZrjllJ+X0M6k5Ccg0yTTn/iRHmtlrtuy
    materials:
      git-1eda989:
        git: https://github.com/edx/edx-gocd-synthetic-testing.git
        type: configrepo
        shallow_clone: false
        auto_update: true
        branch: to-python
      tubular:
        git: https://github.com/edx/tubular
        blacklist:
          - '**/*'
        shallow_clone: true
        auto_update: true
        branch: bszabo/synthetic-testing
        destination: tubular
    stages:
    - release_tests_3:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          run_release_tests:
            timeout: 0
            elastic_profile_id: legacy-default
            tasks:
            - exec:
                arguments:
                - Hello, world
                command: echo
                run_if: passed
          run_release_tests_imported:
            timeout: 0
            elastic_profile_id: legacy-default
            tasks:
                arguments:
                - -c
                - 'alert_opsgenie.py --auth_token $OPSGENIE_API_KEY --alias "gocd-edxapp-pipeline-failure-$GO_PIPELINE_NAME-$GO_STAGE_NAME-$GO_JOB_NAME"
                  --message "[GoCD] edxapp build failed on $GO_PIPELINE_NAME/$GO_STAGE_NAME/$GO_JOB_NAME" --description "Build triggered
                  by $GO_TRIGGER_USER failed at stage $GO_STAGE_NAME on job $GO_JOB_NAME:
                  https://gocd.tools.edx.org/go/pipelines/$GO_PIPELINE_NAME/$GO_PIPELINE_COUNTER/$GO_STAGE_NAME/$GO_STAGE_COUNTER"'
                command: /bin/bash
                working_directory: tubular
                run_if: failed
