format_version: 10
pipelines:
  stage-frontend-app-course-authoring:
    group: st_1_group
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      unused:
        git: https://github.com/edx/edx-gocd-synthetic-testing.git
        type: configrepo
        auto_update: true
        branch: bszabo/frontend-app-authoring-test-gocd
    stages:
      - stage_frontend-app-course-authoring_deploy_frontend:
          jobs:
            run_release_tests_job1:
              timeout: 0
              elastic_profile_id: legacy-default
              tasks:
                - exec:
                    command: bash
                    arguments: ["-c", "exit 0"]  # This will always pass

  release_tests_1_pipeline:
    group: st_1_group
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      upstream:
        pipeline: stage-frontend-app-course-authoring
        stage: stage_frontend-app-course-authoring_deploy_frontend
      git-1eda989:
        git: https://github.com/edx/edx-gocd-synthetic-testing.git
        type: configrepo
        shallow_clone: false
        auto_update: true
        branch: bszabo/frontend-app-authoring-test-gocd
        destination: synthetic-testing
      tubular:
        git: https://github.com/edx/tubular
        blacklist:
          - '**/*'
        shallow_clone: true
        auto_update: true
        branch: bszabo/frontend-app-authoring-test-gocd
        destination: tubular
    environment_variables:
      DATADOG_APP_KEY: "{{SECRET:[gocd-pipelines-sre-managed][DATADOG_APP_KEY]}}"
      DATADOG_API_KEY: "{{SECRET:[gocd-pipelines-sre-managed][DATADOG_API_KEY]}}"
    stages:
    - release_tests_1_stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: true
        jobs:
          run_release_tests_job3:
            timeout: 0
            elastic_profile_id: legacy-default
            tasks:
            - exec:
                arguments:
                - ./tubular/scripts/dd_synthetic_tests.py
                - '--timeout'
                - '600'
                - '--tests'
                - |
                  [
                    {
                        "name": "[Synthetics] edX Smoke Test - [Verified student] A verified student can access a graded course problem",
                        "public_id": "tck-hrr-ubp",
                        "env": "stage",
                        "startUrl": "https://authn.edx.org/login"
                    },
                    {
                        "name": "[Synthetics] edX Smoke Test - [Verified student] An enrolled verified student can access a course's landing page, course content, and course forum",
                        "public_id": "zbz-r28-jjx",
                        "env": "stage",
                        "startUrl": "https://authn.edx.org/login"
                    },
                    {
                        "name": "edX Smoke Test - [Unenrolled student] An unenrolled student cannot load a course's landing page, and sees the \"Enroll Now\" screen",
                        "public_id": "zkx-36f-kui",
                        "env": "stage",
                        "startUrl": "https://authn.edx.org/login"
                    },
                    {
                        "name": "edX Smoke Test - [Anonymous user] An anonymous user is directed to the Logistration page (authn.edx.org) when trying to access content behind log-in wall",
                        "public_id": "6tq-u28-hwa",
                        "env": "stage",
                        "startUrl": "https://learning.stage.edx.org/course/course-v1:edx+gc_22+2024_T1"
                    }
                  ]
                command: python3
                working_directory: tubular
                run_if: passed
